import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Gabarito({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={roboto.className}>
        <nav className="bg-gray-4600 shadow-lg mb-8">
          <div className="flex justify-between max-w-4xl mx-auto py-6 sm:px-6 md:px-8">
            <Link href="/">
              <h1 className="text-2xl font-bold text-white-900">Empresa X</h1>
            </Link>

            <div className="flex items-center space-x-4">
              <img
                src="https://www.gravatar.com/avatar/user123?d=identicon"
                alt="Usuário"
                className="w-8 h-8"
              />
              <div className="text-left flex flex-col text-sm">
                <div>Usuário: Fulano de Tal</div>
                <div>Conta: 123456-7</div>
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
